# Explorer une base de données

Exerçons nous sur Pandas. Cet exercice porte sur le dataset chipotle.csv qui a été utilisé lors de la démo d'utilisation de Pandas.

1. Importez les bonnes librairies

2. Importez le dataset

3. Regardez les 10 premières lignes du dataset

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

4. Quelle est la taille de notre dataset ?

(4622, 5)

5. Affichez toutes les colonnes de notre dataset

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

6. Quel est l’item le plus commandé

     *Indice : On utilisera GROUP BY & Sort_values()*

item_name
Chicken Bowl                             761
Chicken Burrito                          591
Chips and Guacamole                      506
Steak Burrito                            386
Canned Soft Drink                        351
Chips                                    230
Steak Bowl                               221
Bottled Water                            211
Chips and Fresh Tomato Salsa             130
Canned Soda                              126
Chicken Salad Bowl                       123
Chicken Soft Tacos                       120
Side of Chips                            110
Veggie Burrito                            97
Barbacoa Burrito                          91
Veggie Bowl                               87
Carnitas Bowl                             71
Barbacoa Bowl                             66
Carnitas Burrito                          60
Steak Soft Tacos                          56
6 Pack Soft Drink                         55
Chips and Tomatillo Red Chili Salsa       50
Chicken Crispy Tacos                      50
Chips and Tomatillo Green Chili Salsa     45
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        36
Chips and Tomatillo-Green Chili Salsa     33
Steak Salad Bowl                          31
Nantucket Nectar                          29
Chips and Tomatillo-Red Chili Salsa       25
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        23
Izze                                      20
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Barbacoa Crispy Tacos                     12
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Veggie Soft Tacos                          8
Carnitas Crispy Tacos                      8
Burrito                                    6
Carnitas Salad Bowl                        6
Veggie Salad                               6
Steak Salad                                4
Bowl                                       4
Salad                                      2
Crispy Tacos                               2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: quantity, dtype: int64

7. Combien d’items ont été commandés au total chez Chipotle

4972

8. Combien de chiffre d’affaire à realisé Chipotle ?
      
      A. Convertissez item_price en nombre décimal
        1. Regardez dataset[“item_price”], que voyez vous ?
        2. Trouvons un moyen d’enlever ce $ qui nous gène. Pour cela, on peut utiliser [str](https://bit.ly/2ClcdtN)
        3. Convertissons maintenant la série en float au lieu de string
        
    B. Multipliez la quantité vendues par le prix de l’item
    
    C. Faites la somme du tout, combien trouvez vous?
    
    D. Arrondissez à deux chiffres après la virgule
    
        1. On pourra utiliser la fonction [Series.round()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.round.html#pandas.Series.round)

39237.02

9. Quel est le revenu moyen par commande ?

21.39423118865867